/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Register;

import Business.AppointmentControl;
import Business.Person.Doctor;
import Business.Person.Patient;
import Business.Role.DoctorRole;
import Business.Role.PatientRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import DataManagement.DatabaseFactory;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Alex
 */
public class RegisterJDialog extends javax.swing.JDialog {

    UserAccountDirectory userAccountDirectory;

    /**
     * Creates new form RegisterJDialog
     */
    public RegisterJDialog(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.userAccountDirectory = AppointmentControl.getInstance().getUserAccountDirectory();
        panelDoctor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupRole = new javax.swing.ButtonGroup();
        panelDoctor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtResearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        spinnerOfficeHour = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbPatient = new javax.swing.JRadioButton();
        rbDoctor = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinnerDOB = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEMail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        panelDoctor.setLayout(jPanel2Layout);

        jLabel7.setText("Research Area:");
        jLabel7.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDoctor.add(jLabel7, gridBagConstraints);

        txtResearch.setMaximumSize(new java.awt.Dimension(200, 20));
        txtResearch.setMinimumSize(new java.awt.Dimension(200, 20));
        txtResearch.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDoctor.add(txtResearch, gridBagConstraints);

        jLabel8.setText("Office Hour:");
        jLabel8.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDoctor.add(jLabel8, gridBagConstraints);

        spinnerOfficeHour.setModel(new javax.swing.SpinnerDateModel());
        spinnerOfficeHour.setMaximumSize(new java.awt.Dimension(200, 20));
        spinnerOfficeHour.setMinimumSize(new java.awt.Dimension(200, 20));
        spinnerOfficeHour.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDoctor.add(spinnerOfficeHour, gridBagConstraints);

        jLabel9.setText("Title:");
        jLabel9.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDoctor.add(jLabel9, gridBagConstraints);

        txtTitle.setMaximumSize(new java.awt.Dimension(200, 20));
        txtTitle.setMinimumSize(new java.awt.Dimension(200, 20));
        txtTitle.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDoctor.add(txtTitle, gridBagConstraints);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Role:");
        jLabel1.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        buttonGroupRole.add(rbPatient);
        rbPatient.setSelected(true);
        rbPatient.setText("Patient");
        rbPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPatientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rbPatient, gridBagConstraints);

        buttonGroupRole.add(rbDoctor);
        rbDoctor.setText("Doctor");
        rbDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoctorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rbDoctor, gridBagConstraints);

        jLabel2.setText("First Name:");
        jLabel2.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtFirstName.setMaximumSize(new java.awt.Dimension(200, 20));
        txtFirstName.setMinimumSize(new java.awt.Dimension(200, 20));
        txtFirstName.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtFirstName, gridBagConstraints);

        jLabel3.setText("Last Name:");
        jLabel3.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtLastName.setMaximumSize(new java.awt.Dimension(200, 20));
        txtLastName.setMinimumSize(new java.awt.Dimension(200, 20));
        txtLastName.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtLastName, gridBagConstraints);

        jLabel4.setText("Date Of Birth:");
        jLabel4.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        spinnerDOB.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spinnerDOB.setMaximumSize(new java.awt.Dimension(200, 20));
        spinnerDOB.setMinimumSize(new java.awt.Dimension(200, 20));
        spinnerDOB.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(spinnerDOB, gridBagConstraints);

        jLabel5.setText("Ssn:");
        jLabel5.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        txtSsn.setMaximumSize(new java.awt.Dimension(200, 20));
        txtSsn.setMinimumSize(new java.awt.Dimension(200, 20));
        txtSsn.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtSsn, gridBagConstraints);

        jLabel6.setText("E-Mail:");
        jLabel6.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        txtEMail.setMaximumSize(new java.awt.Dimension(200, 20));
        txtEMail.setMinimumSize(new java.awt.Dimension(200, 20));
        txtEMail.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtEMail, gridBagConstraints);

        jLabel10.setText("Password:");
        jLabel10.setMaximumSize(new java.awt.Dimension(95, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(95, 14));
        jLabel10.setPreferredSize(new java.awt.Dimension(95, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel10, gridBagConstraints);

        txtPassword.setMaximumSize(new java.awt.Dimension(200, 20));
        txtPassword.setMinimumSize(new java.awt.Dimension(200, 20));
        txtPassword.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtPassword, gridBagConstraints);

        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSubmit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        Date date = ((SpinnerDateModel) spinnerDOB.getModel()).getDate();
        String ssn = txtSsn.getText().trim();
        String email = txtEMail.getText().trim();
        char[] tempPassword = txtPassword.getPassword();
        String password = String.valueOf(tempPassword);
        if (firstName.equals("") || lastName.equals("") || date == null || ssn.equals("") || email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid Input.");
            return;
        }
        if (rbPatient.isSelected()) {
            Patient patient = new Patient();
            patient.setFirstName(firstName);
            patient.setLastName(lastName);
            patient.setDateOfBirth(date);
            patient.setSsn(ssn);
            patient.setEmail(email);

            UserAccount ua = this.userAccountDirectory.addUserAccount();
            ua.setAccountName(email);
            ua.setIsActive(true);
            ua.setPassword(password);
            ua.setPerson(patient);
            ua.setRole(new PatientRole());
        } else {
            String researchArea = txtResearch.getText().trim();
            Date officeHour = ((SpinnerDateModel) spinnerOfficeHour.getModel()).getDate();
            String title = txtTitle.getText().trim();
            if (researchArea.equals("") || officeHour == null || title.equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid Input.");
                return;
            }
            Doctor doctor = new Doctor();
            doctor.setFirstName(firstName);
            doctor.setLastName(lastName);
            doctor.setDateOfBirth(date);
            doctor.setSsn(ssn);
            doctor.setEmail(email);
            doctor.setTitle(title);
            doctor.setOfficeHour(officeHour);
            doctor.setResearchArea(researchArea);

            UserAccount ua1 = this.userAccountDirectory.addUserAccount();
            ua1.setAccountName(email);
            ua1.setIsActive(true);
            ua1.setPassword(password);
            ua1.setPerson(doctor);
            ua1.setRole(new DoctorRole());
        }
        DatabaseFactory.getInstance().storeSystem();
        JOptionPane.showMessageDialog(null, "Account creste successfully.");
        this.dispose();
    }//GEN-LAST:event_btSubmitActionPerformed

    private void rbPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPatientActionPerformed
        // TODO add your handling code here:
        panelDoctor.setVisible(false);

    }//GEN-LAST:event_rbPatientActionPerformed

    private void rbDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoctorActionPerformed
        // TODO add your handling code here:
        panelDoctor.setVisible(true);
    }//GEN-LAST:event_rbDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmit;
    private javax.swing.ButtonGroup buttonGroupRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDoctor;
    private javax.swing.JRadioButton rbDoctor;
    private javax.swing.JRadioButton rbPatient;
    private javax.swing.JSpinner spinnerDOB;
    private javax.swing.JSpinner spinnerOfficeHour;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtResearch;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
