/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkarea;

import Business.Appointment.Appointment;
import Business.AppointmentControl;
import Business.Person.Doctor;
import Business.Person.Staff;
import Business.UserAccount.UserAccount;
import DataManagement.DatabaseFactory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class DoctorWorkareaJPanel extends javax.swing.JPanel {

    AppointmentControl appointmentControl;
    UserAccount userAccount;
    private JPanel userProcessContainer;
    private javax.swing.JFrame parent;

    /**
     * Creates new form DoctorWorkareaJPanel
     */
    public DoctorWorkareaJPanel(JPanel userProcessContainer, UserAccount userAccount, javax.swing.JFrame parent) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.parent = parent;
        appointmentControl = AppointmentControl.getInstance();
        populateInfoField();
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Appointment.getModel();
        dtm.setRowCount(0);
        for (Appointment a : appointmentControl.getAppointmentHistory().getDoctorAppointmentList((Doctor) userAccount.getPerson())) {
            Object[] row = new Object[3];
            row[0] = a;
            row[1] = a.getDateTime();
            row[2] = a.getStatus();
            dtm.addRow(row);
        }
    }

    private void populateInfoField() {
        
        lbname.setText(userAccount.getPerson().getFullName());
        lbEID.setText(((Staff) userAccount.getPerson()).getEmployeeId());
        lbTitle.setText(((Doctor) userAccount.getPerson()).getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BackGround = new javax.swing.JPanel();
        Information = new javax.swing.JPanel();
        lb11 = new javax.swing.JLabel();
        lb21 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbEID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Appointment = new javax.swing.JTable();
        Button = new javax.swing.JPanel();
        btViewAppointment = new javax.swing.JButton();
        btAction = new javax.swing.JButton();
        btLogoff = new javax.swing.JButton();
        lbPortrait = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        Information.setLayout(new java.awt.GridBagLayout());

        lb11.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Information.add(lb11, gridBagConstraints);

        lb21.setText("EID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Information.add(lb21, gridBagConstraints);

        lbname.setText("****************");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Information.add(lbname, gridBagConstraints);

        lbEID.setText("****************");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Information.add(lbEID, gridBagConstraints);

        jLabel1.setText("Title:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Information.add(jLabel1, gridBagConstraints);

        lbTitle.setText("****************");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Information.add(lbTitle, gridBagConstraints);

        tbl_Appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date/Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Appointment.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbl_Appointment);
        if (tbl_Appointment.getColumnModel().getColumnCount() > 0) {
            tbl_Appointment.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_Appointment.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        Button.setLayout(new java.awt.GridBagLayout());

        btViewAppointment.setText("View");
        btViewAppointment.setMaximumSize(new java.awt.Dimension(50, 50));
        btViewAppointment.setMinimumSize(new java.awt.Dimension(50, 50));
        btViewAppointment.setPreferredSize(new java.awt.Dimension(70, 50));
        btViewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewAppointmentActionPerformed(evt);
            }
        });
        Button.add(btViewAppointment, new java.awt.GridBagConstraints());

        btAction.setText("Action");
        btAction.setMaximumSize(new java.awt.Dimension(50, 50));
        btAction.setMinimumSize(new java.awt.Dimension(50, 50));
        btAction.setPreferredSize(new java.awt.Dimension(70, 50));
        btAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionActionPerformed(evt);
            }
        });
        Button.add(btAction, new java.awt.GridBagConstraints());

        btLogoff.setText("Logoff");
        btLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoffActionPerformed(evt);
            }
        });

        lbPortrait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorWorkarea/doctor.jpg"))); // NOI18N

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLogoff)
                            .addGroup(BackGroundLayout.createSequentialGroup()
                                .addComponent(lbPortrait)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPortrait))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogoff)
                .addContainerGap())
        );

        jPanel1.add(BackGround, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btViewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewAppointmentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_Appointment.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        Appointment appointment = (Appointment) tbl_Appointment.getValueAt(selectedRow, 0);
        ViewDoctorAppointmentJDialog jdialog = new ViewDoctorAppointmentJDialog(parent, true, appointment, appointmentControl.getUserAccountDirectory().getDoctorAccount());
        jdialog.setVisible(true);

    }//GEN-LAST:event_btViewAppointmentActionPerformed

    private void btActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_Appointment.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        Appointment appointment = (Appointment) tbl_Appointment.getValueAt(selectedRow, 0);
        if (appointment.getStatus().equals(Appointment.StatusType.Cancelled)) {
            JOptionPane.showMessageDialog(null, "This appointment is already cancelled by patient.");
            return;
        } else if (appointment.getStatus().equals(Appointment.StatusType.Closed)) {
            JOptionPane.showMessageDialog(null, "This appointment is already closed status.");
            return;
        }
        appointment.action();
        DatabaseFactory.getInstance().storeSystem();
        populateTable();
    }//GEN-LAST:event_btActionActionPerformed

    private void btLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoffActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btLogoffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Button;
    private javax.swing.JPanel Information;
    private javax.swing.JButton btAction;
    private javax.swing.JButton btLogoff;
    private javax.swing.JButton btViewAppointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb21;
    private javax.swing.JLabel lbEID;
    private javax.swing.JLabel lbPortrait;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbname;
    private javax.swing.JTable tbl_Appointment;
    // End of variables declaration//GEN-END:variables
}
